// @ts-nocheck
import { default as __fd_glob_57 } from "../content/docs/user-guide/meta.json?collection=meta"
import { default as __fd_glob_56 } from "../content/docs/legal/meta.json?collection=meta"
import { default as __fd_glob_55 } from "../content/docs/database/meta.json?collection=meta"
import { default as __fd_glob_54 } from "../content/docs/iot-device/meta.json?collection=meta"
import { default as __fd_glob_53 } from "../content/docs/architecture/meta.json?collection=meta"
import { default as __fd_glob_52 } from "../content/docs/getting-started/meta.json?collection=meta"
import { default as __fd_glob_51 } from "../content/docs/frontend/meta.json?collection=meta"
import { default as __fd_glob_50 } from "../content/docs/admin-guide/meta.json?collection=meta"
import { default as __fd_glob_49 } from "../content/docs/deployment/meta.json?collection=meta"
import { default as __fd_glob_48 } from "../content/docs/api-reference/meta.json?collection=meta"
import { default as __fd_glob_47 } from "../content/docs/meta.json?collection=meta"
import * as __fd_glob_46 from "../content/docs/iot-device/sensor-stream-format.mdx?collection=docs"
import * as __fd_glob_45 from "../content/docs/iot-device/index.mdx?collection=docs"
import * as __fd_glob_44 from "../content/docs/iot-device/firmware-guide.mdx?collection=docs"
import * as __fd_glob_43 from "../content/docs/iot-device/fall-detection.mdx?collection=docs"
import * as __fd_glob_42 from "../content/docs/iot-device/device-status.mdx?collection=docs"
import * as __fd_glob_41 from "../content/docs/user-guide/troubleshooting.mdx?collection=docs"
import * as __fd_glob_40 from "../content/docs/user-guide/health-tips.mdx?collection=docs"
import * as __fd_glob_39 from "../content/docs/user-guide/faq.mdx?collection=docs"
import * as __fd_glob_38 from "../content/docs/getting-started/running-locally.mdx?collection=docs"
import * as __fd_glob_37 from "../content/docs/getting-started/installation.mdx?collection=docs"
import * as __fd_glob_36 from "../content/docs/getting-started/index.mdx?collection=docs"
import * as __fd_glob_35 from "../content/docs/getting-started/environment-variables.mdx?collection=docs"
import * as __fd_glob_34 from "../content/docs/legal/terms-of-service.mdx?collection=docs"
import * as __fd_glob_33 from "../content/docs/legal/privacy-policy.mdx?collection=docs"
import * as __fd_glob_32 from "../content/docs/legal/accessibility.mdx?collection=docs"
import * as __fd_glob_31 from "../content/docs/frontend/patient-dashboard.mdx?collection=docs"
import * as __fd_glob_30 from "../content/docs/frontend/index.mdx?collection=docs"
import * as __fd_glob_29 from "../content/docs/frontend/caregiver-dashboard.mdx?collection=docs"
import * as __fd_glob_28 from "../content/docs/frontend/auth-pages.mdx?collection=docs"
import * as __fd_glob_27 from "../content/docs/frontend/admin-dashboard.mdx?collection=docs"
import * as __fd_glob_26 from "../content/docs/deployment/vercel.mdx?collection=docs"
import * as __fd_glob_25 from "../content/docs/deployment/index.mdx?collection=docs"
import * as __fd_glob_24 from "../content/docs/deployment/docker.mdx?collection=docs"
import * as __fd_glob_23 from "../content/docs/architecture/iot-pipeline.mdx?collection=docs"
import * as __fd_glob_22 from "../content/docs/architecture/index.mdx?collection=docs"
import * as __fd_glob_21 from "../content/docs/architecture/database-adapter-pattern.mdx?collection=docs"
import * as __fd_glob_20 from "../content/docs/architecture/auth-flow.mdx?collection=docs"
import * as __fd_glob_19 from "../content/docs/database/schema-overview.mdx?collection=docs"
import * as __fd_glob_18 from "../content/docs/database/prisma-vs-convex.mdx?collection=docs"
import * as __fd_glob_17 from "../content/docs/database/models.mdx?collection=docs"
import * as __fd_glob_16 from "../content/docs/database/index.mdx?collection=docs"
import * as __fd_glob_15 from "../content/docs/api-reference/profile.mdx?collection=docs"
import * as __fd_glob_14 from "../content/docs/api-reference/patients.mdx?collection=docs"
import * as __fd_glob_13 from "../content/docs/api-reference/messages.mdx?collection=docs"
import * as __fd_glob_12 from "../content/docs/api-reference/index.mdx?collection=docs"
import * as __fd_glob_11 from "../content/docs/api-reference/health.mdx?collection=docs"
import * as __fd_glob_10 from "../content/docs/api-reference/falls.mdx?collection=docs"
import * as __fd_glob_9 from "../content/docs/api-reference/devices.mdx?collection=docs"
import * as __fd_glob_8 from "../content/docs/api-reference/caregivers.mdx?collection=docs"
import * as __fd_glob_7 from "../content/docs/api-reference/auth.mdx?collection=docs"
import * as __fd_glob_6 from "../content/docs/api-reference/admin.mdx?collection=docs"
import * as __fd_glob_5 from "../content/docs/admin-guide/user-management.mdx?collection=docs"
import * as __fd_glob_4 from "../content/docs/admin-guide/system-logs.mdx?collection=docs"
import * as __fd_glob_3 from "../content/docs/admin-guide/index.mdx?collection=docs"
import * as __fd_glob_2 from "../content/docs/admin-guide/fall-management.mdx?collection=docs"
import * as __fd_glob_1 from "../content/docs/admin-guide/device-management.mdx?collection=docs"
import * as __fd_glob_0 from "../content/docs/index.mdx?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.doc("docs", "content/docs", {"index.mdx": __fd_glob_0, "admin-guide/device-management.mdx": __fd_glob_1, "admin-guide/fall-management.mdx": __fd_glob_2, "admin-guide/index.mdx": __fd_glob_3, "admin-guide/system-logs.mdx": __fd_glob_4, "admin-guide/user-management.mdx": __fd_glob_5, "api-reference/admin.mdx": __fd_glob_6, "api-reference/auth.mdx": __fd_glob_7, "api-reference/caregivers.mdx": __fd_glob_8, "api-reference/devices.mdx": __fd_glob_9, "api-reference/falls.mdx": __fd_glob_10, "api-reference/health.mdx": __fd_glob_11, "api-reference/index.mdx": __fd_glob_12, "api-reference/messages.mdx": __fd_glob_13, "api-reference/patients.mdx": __fd_glob_14, "api-reference/profile.mdx": __fd_glob_15, "database/index.mdx": __fd_glob_16, "database/models.mdx": __fd_glob_17, "database/prisma-vs-convex.mdx": __fd_glob_18, "database/schema-overview.mdx": __fd_glob_19, "architecture/auth-flow.mdx": __fd_glob_20, "architecture/database-adapter-pattern.mdx": __fd_glob_21, "architecture/index.mdx": __fd_glob_22, "architecture/iot-pipeline.mdx": __fd_glob_23, "deployment/docker.mdx": __fd_glob_24, "deployment/index.mdx": __fd_glob_25, "deployment/vercel.mdx": __fd_glob_26, "frontend/admin-dashboard.mdx": __fd_glob_27, "frontend/auth-pages.mdx": __fd_glob_28, "frontend/caregiver-dashboard.mdx": __fd_glob_29, "frontend/index.mdx": __fd_glob_30, "frontend/patient-dashboard.mdx": __fd_glob_31, "legal/accessibility.mdx": __fd_glob_32, "legal/privacy-policy.mdx": __fd_glob_33, "legal/terms-of-service.mdx": __fd_glob_34, "getting-started/environment-variables.mdx": __fd_glob_35, "getting-started/index.mdx": __fd_glob_36, "getting-started/installation.mdx": __fd_glob_37, "getting-started/running-locally.mdx": __fd_glob_38, "user-guide/faq.mdx": __fd_glob_39, "user-guide/health-tips.mdx": __fd_glob_40, "user-guide/troubleshooting.mdx": __fd_glob_41, "iot-device/device-status.mdx": __fd_glob_42, "iot-device/fall-detection.mdx": __fd_glob_43, "iot-device/firmware-guide.mdx": __fd_glob_44, "iot-device/index.mdx": __fd_glob_45, "iot-device/sensor-stream-format.mdx": __fd_glob_46, });

export const meta = await create.meta("meta", "content/docs", {"meta.json": __fd_glob_47, "api-reference/meta.json": __fd_glob_48, "deployment/meta.json": __fd_glob_49, "admin-guide/meta.json": __fd_glob_50, "frontend/meta.json": __fd_glob_51, "getting-started/meta.json": __fd_glob_52, "architecture/meta.json": __fd_glob_53, "iot-device/meta.json": __fd_glob_54, "database/meta.json": __fd_glob_55, "legal/meta.json": __fd_glob_56, "user-guide/meta.json": __fd_glob_57, });